In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('ipldata_19/matches.csv')

In [3]:
matches.shape

(756, 18)

In [4]:
matches.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [5]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [6]:
pd.value_counts(matches['season'])

2013    76
2012    74
2011    73
2019    60
2018    60
2016    60
2014    60
2010    60
2017    59
2015    59
2008    58
2009    57
Name: season, dtype: int64

In [7]:
pd.value_counts(matches['winner'])

Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Delhi Capitals                  10
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: winner, dtype: int64

In [14]:
matches.drop_duplicates('season',keep='last')[['season','winner']].reset_index(drop=True)

    season                 winner
0     2017         Mumbai Indians
1     2008       Rajasthan Royals
2     2009        Deccan Chargers
3     2010    Chennai Super Kings
4     2011    Chennai Super Kings
5     2012  Kolkata Knight Riders
6     2013         Mumbai Indians
7     2014  Kolkata Knight Riders
8     2015         Mumbai Indians
9     2016    Sunrisers Hyderabad
10    2018    Chennai Super Kings
11    2019         Mumbai Indians

In [15]:
matches[matches['player_of_match'] == 'MS Dhoni'][['team1','team2','player_of_match']]

                           team1                        team2 player_of_match
24           Sunrisers Hyderabad       Rising Pune Supergiant        MS Dhoni
73           Chennai Super Kings  Royal Challengers Bangalore        MS Dhoni
86              Delhi Daredevils          Chennai Super Kings        MS Dhoni
143          Chennai Super Kings              Deccan Chargers        MS Dhoni
181          Chennai Super Kings        Kolkata Knight Riders        MS Dhoni
227              Kings XI Punjab          Chennai Super Kings        MS Dhoni
288          Chennai Super Kings             Delhi Daredevils        MS Dhoni
378          Chennai Super Kings               Mumbai Indians        MS Dhoni
413          Sunrisers Hyderabad          Chennai Super Kings        MS Dhoni
421          Chennai Super Kings                Pune Warriors        MS Dhoni
445          Chennai Super Kings             Delhi Daredevils        MS Dhoni
509  Royal Challengers Bangalore          Chennai Super Kings        MS Dhoni
628              Kings XI Punjab      Rising Pune Supergiants        MS Dhoni
659  Royal Challengers Bangalore          Chennai Super Kings        MS Dhoni
707          Chennai Super Kings             Rajasthan Royals        MS Dhoni
720             Rajasthan Royals          Chennai Super Kings        MS Dhoni
745          Chennai Super Kings               Delhi Capitals        MS Dhoni